- Cargo.toml
- src/client.rs
- src/lib.rs
without these changes you can't for example run:
`cargo run --example ssl --no-default-features --features use-openssl --features proxy`
because `Client` is built only with with default features, but having the combination of SSL and proxy is enough for the client to run.
to avoid repeating the cfg before Client, impl Client and impl ElectrumApi the cfg has been moved at module level
it also change the Cargo toml to recall features instead of repeating deps for the default feature
> allow Client with openssl+proxy

- Cargo.toml
Will appreciate new release - required for publishing downstream crates to `crates.io`
> Updating to rust-bitcoin 0.26

- src/api.rs
- src/client.rs
- src/raw_client.rs
Currently compilation with `--all-features` and `--feature debug-calls` or `cargo test` is broken. This PR fixes it
> Fixing calls_made fn signature

- src/types.rs
Some servers like electrs return the unconfirmed balance for an address as a
negative value.
Closes #45
> Make `unconfirmed` an `i64`

- src/client.rs
The first patch fixes #47 by properly comparing the number of failed attempts with the value of config.retry.
The second patch improves the logging that happens as part of this logic.
> Rework retry logic within `impl_inner_call`

- .github/workflows/cont_integration.yml
`cargo test --all` is a deprecated equivalent of `cargo test --workspace`. This leads to the fact that tests are run without using all features (utilizing default set of features only) and such bugs as #32 missed by CI.
> Fix CI testing for all features

- src/raw_client.rs
- src/stream.rs
- src/types.rs
PR removes 16 (!) `unwraps()` which are unnecessary and were already covered by an error case.
This is quite important for the overall library stability
> Getting rid of lock().unwrap()

- src/raw_client.rs
This improves overall function code style & allows to remove two unnecessary unwraps and one implicit panic. Together with #33 this makes this library unwrap-free and stable (i.e. not causing the software using it to unexpectedly terminate instead or reporting error to the calling function)
> Streamlining batch_call and removing unnecessary unwraps()

- Cargo.toml
Simply updating `rust-bitcoin` dependency to latest
> bump rust-bitcoin to v0.27

- src/config.rs
The intention is to reduce some confusion on how to manipulate `Config`.
The alternative is to make `Config` fields public.
> Add `Config::builder` method

- src/api.rs
- src/batch.rs
- src/client.rs
- src/raw_client.rs
- src/types.rs
In order to give more flexibility to the users of this library I added a `raw_call` method to the `ElectrumApi` trait that will allow to call any arbitrary electrum API call.
> Add raw_call to ElectrumApi

- Cargo.toml
- src/client.rs
- src/config.rs
- src/lib.rs
- src/raw_client.rs
- src/socks/mod.rs
- src/socks/v4.rs
- src/socks/v5.rs
- src/socks/writev.rs
- src/types.rs
To achieve this we have to include a modified socks library, with supports for
timeout
Remove the error `BothSocksAndTimeout` which isn't needed anymore
> Implement timeout for socks connection

- src/raw_client.rs
This fixes a supposed deadlock when the reader thread receives a script subscription notification from the server before it receives a subscribing response. 
I am not 100% sure if this actually fixes a deadlock, but I ran into this in a regtest setup where a bunch of subscriptions were made, while some script notifications could be processed in parallel. My test failed sporadically with the electrum client locking up completely and adding this drop made the tests consistently pass again.
> Client: Drop script subscriptions to free lock

- src/raw_client.rs
This reverts commit 0e3e6325e65749c0446fbede99d763b98321362d.
This has been causing issues with tests timing out
> Revert "Ignore empty lines"

- Cargo.toml
- src/raw_client.rs
- src/socks/v5.rs
This version bump for `bitcoin` dependency is required to fix https://github.com/bitcoindevkit/bdk/issues/646.
> Bump bitcoin dependency to ^0.29, minor related fixes

- examples/tor.rs
- src/client.rs
- src/config.rs
The `Result` was necessary in the past because they couldn't both be set,
this is not true anymore after 7493630ed88af5558b84a1f715890f67cfa4ec24
> `timeout()` and `socks()` don't return Result

- src/api.rs
- src/batch.rs
- src/client.rs
- src/raw_client.rs
script_subscribe call hasn't the batch counterpart which may be convenient for multiple subsequent subscribe.
> Implement batch call for script subscribe

- src/client.rs
Users may leverage the Error to avoid remembering client-side the subscription status. eg. Always subscribing and calling script_pop in case AlreadySubscribed is returned.
Backport for version 0.14.0
> Retry client should return AlreadySubscribed error

- src/raw_client.rs
- src/types.rs
the opposite, erroring when subscribing multiple times, is not handled because clients could call multiple times to trigger the server to reply with the tip
> Errors if expecting headers notification but not subscribed

- Cargo.toml
Update the `rustls` dependency to version 0.21 and bump the version of this crate to 0.16 so the change can be released.
I don't know what stage in your release cycle you guys are up to so I put the version bump as a separate patch - can drop it if not needed.
Done to help with https://github.com/bitcoindevkit/rust-esplora-client/pull/51
> Update rustls dependency

- src/batch.rs
- src/config.rs
- src/types.rs
Being able to add raw requests to `Batch` makes sense from an API standpoint because we already allow raw non-batched requests. This is also useful when the electrum server API gets an updated version and our client is unable to keep up.
Additional to this, I have improved the documentation and made `Call` private (since `Call` is never used externally).
> Add `Batch::raw` and improve docs

- Cargo.toml
- src/lib.rs
- src/raw_client.rs
I noticed that `webpki` dependency is no longer maintained and that has a high severity vulnerability. 
This PR remove the `webpki` dependency and bump `webpki-roots` to v0.25
> Remove `webpki` and bump `webpki-roots` to `v0.25`

- src/lib.rs
- src/raw_client.rs
- src/types.rs
- src/utils.rs
I recently needed to validate a Merkle inclusion proof as retrieved via `transaction_get_merkle`. 
As I figured it might be useful to other people, too, we add it here as a simple utility method.
> Add utility to validate `GetMerkleRes`

- Cargo.toml
- src/lib.rs
- src/raw_client.rs
- src/types.rs
Upgrade bitcoin dependency to `rust-bitcoin v0.31.0-rc1`:
Allows us to remove the dependency on `bitcoin-private` because the `hex` stuff is exposed by `bitcoin` now.
> Upgrade bitcoin

- src/socks/v5.rs
This PR fixes a bug which excepted initial SOCKS5 proxy connection attempts from the punctual enforcement of timeouts. 
Before this change, invoking `Socks5Stream::connect` (or `Socks5Stream::connect_with_password`) could block for much longer than the configured timeout. In practice, this manifested as `Client::from_config` apparently failing to respect the timeout specified in the `Config` passed to it. AFAICT this only applied to SOCKS proxy connections.
To demonstrate, here is a simple example program which attempts to connect to an unreachable electrum server with a 10 second timeout.  
```rust
use electrum_client::{Client, ConfigBuilder, Socks5Config};
fn main() {
let proxy = Socks5Config::new("127.0.0.1:9050");
let config = ConfigBuilder::new()
.socks5(Some(proxy)) …
```
> enforce timeout on initial socks5 proxy connection

- CHANGELOG.md
- Cargo.toml
Besides bumping the version I've also added a simple changelog that list the PRs in this (0.19.0) and the prior (0.18.0) release. The main reason for this release is the bump of the rust-bitcoin version to 0.31.0 which is needed to upgrade dependent projects like bdk to also use rust-bitcoin 0.31.0.
> Bump version to 0.19.0 and add CHANGELOG.md

- Cargo.toml
- src/raw_client.rs
With rustls 0.23 there is no longer a dependency on ring, allowing easier compilation for various targets.
Not super confident with my updates to `ServerCertVerifier` and `Der` of certificates (is this being tested?), needs review.
> Upgrade rustls to 0.23

- Cargo.toml
partially fixes [#1422](https://github.com/bitcoindevkit/bdk/issues/1422)
It updates the rust-bitcoin to 0.32.0, the `bitcoin` crate dependency.
_NOTE: The overall BDK update to `0.32.0` still requires and depends on some other crates, please refer to [#1422](https://github.com/bitcoindevkit/bdk/issues/1422)._
It's open for any comments.
- Update the `bitcoin` crate dependency to `0.32.0`
> chore(deps): upgrade `rust-bitcoin` to `0.32.0`

- .github/workflows/cont_integration.yml
- Cargo.toml
- README.md
Since the main BDK crates are changing to MSRV 1.63.0 as is LDK the CI for this project should also have an MSRV and test against it in CI.
Also rustc 1.63 is the version shipped with the current debian stable (bookworm): https://packages.debian.org/stable/rust/rustc
> ci: add test with MSRV 1.63.0

- .github/workflows/cont_integration.yml
- Cargo.toml
- src/lib.rs
- src/raw_client.rs
- src/types.rs
This PR adds the ability to build the client using the `ring` dependency for `rustls` instead of the new default `aws-lc-rs`.
As of the [`0.23.0` release](https://github.com/rustls/rustls/releases/tag/v%2F0.23.0), rustls changed its default cryptography provider to [aws-lc-rs](https://crates.io/crates/aws-lc-rs). This new library is actually a set of bindings to a C library maintained by AWS, and they provide prebuilt bindings for [some platforms](https://aws.github.io/aws-lc-rs/platform_support.html) but not all. On these other platforms, the compilation step will attempt to build the bindings, requiring extra dependencies (CMake, libclang and others depending on the platform). This compilation step is what is currently breaking our Android and Swift builds for bdk-ffi. It is certainly …
> Add use-rustls-ring feature

- CHANGELOG.md
- Cargo.toml
Bumped crate version to 0.21.0 and added below to changelog:
- Add use-rustls-ring feature #135
- refactor: make validate_merkle_proof more efficient #134
- chore: set rust edition to 2021, fix clippy, add ci fmt and clippy checks #139
- Upgrade rustls to 0.23 #132
- chore(deps): upgrade rust-bitcoin to 0.32.0 #133
- ci: add test with MSRV 1.63.0 #128
> Bump version to 0.21.0 and update CHANGELOG.md

- src/raw_client.rs
fixes #149 https://github.com/bitcoindevkit/bdk/issues/1598
It has been noticed some issues by both users and developers, as reported in #149, https://github.com/bitcoindevkit/bdk/issues/1598 and https://github.com/wizardsardine/liana/issues/1300, when using the library with `use-rustls-{ring}` feature to connect to electrum servers that use self-signed certificates, there are even some issues when trying to connect to `ssl://electrum.blockstream.info:50002` server. 
To connect in an insecure manner either with `rustls` or `openssl` features, the user can set the `validate_domain` field in the `Config` to false, this will either set the `SslVerifyMode::NONE` when using `openssl`, or use the custom `NoCertificateVerification` for the 
`rustls::client::danger::ServerCertVerifier` trait when …
> fix(insecure-tls): `NoCertificateVerification` implementation

- src/api.rs
- src/client.rs
- src/raw_client.rs
- src/types.rs
This PR introduces the `blockchain.transaction.id_from_pos` feature from Electrum. This functionality is essential for an ongoing implementation in `bdk_electrum`, which requires retrieving the coinbase transaction from a block at a specified `height`. Currently, there is no straightforward method to achieve this. By implementing the `id_from_pos` feature, we will effectively address this gap.
> feat: add `id_from_pos` support

- .github/workflows/cont_integration.yml
- README.md
I'm not thrilled about having to pin `rustls` to meet our MSRV, but we need to make a new release and can't count on rustls/rustls#2239 being accepted by the `rustls` team.
> ci: pin msrv dep version for rustls

- .github/workflows/cont_integration.yml
- CHANGELOG.md
- Cargo.toml
- README.md
`rustls` versions 0.23.18 and 0.23.19 contains fix for vulnerability RUSTSEC-2024-0399. However, 0.23.18 bumps MSRV to 1.71. 0.23.19 reverts MSRV back to 1.63.
We enforce min `rustls` version to 0.23.19 to make it easier to compile on MSRV and ensure we include the RUSTSEC-2024-0399 fix.
Note that in CI, I decided to pin `rustls` dependency to 0.23.19 explicitly. This is because in future versions of `rustls`, the MSRV will be changed to 1.71.
Context: https://github.com/rustls/rustls/pull/2244
> chore: Enforce min `rustls` version to 0.23.19

- src/api.rs
This is an alternative and non-breaking alternative to https://github.com/bitcoindevkit/bdk/pull/1820.
> Allow types that reference `ElectrumApi` to also implement `ElectrumApi`

- .github/workflows/cont_integration.yml
- src/raw_client.rs
Fixes issue #75 
This is my first open source pull request so I apologize for any formatting issues. Additionally, I don't know the repository as well as others so there may be a better way to implement the fix.
I believe I found the root cause of this. I added a pull request to fix, but I'm going to copy/paste what I believe is causing the error.
The main issue in the code is inside raw_client.rs inside the `recv` method implementation (snippet below):
https://github.com/bitcoindevkit/rust-electrum-client/blob/805ea0af307e6465f23c2d7f25a32d7ff61fe7ec/src/raw_client.rs#L671-L685
When this is first called, the `self._reader_thread` will run. Inside the `self._reader_thread`, if the request id matches the response id, everything works fine. However, if the request id does not match the …
> fix: fix batch ordering issue

- .github/workflows/cont_integration.yml
- CHANGELOG.md
- Cargo.toml
fixes #168 
- updates the CI to run on `ubuntu-latest` GitHub runner, as the previously used `ubuntu-20.04` has been officially deprecated as of 2025-04-15, see: https://github.com/actions/runner-images/issues/11101.
- updates the project version to `0.23.1`.
- updates the `CHANGELOG.md` with changes to latest version.
> chore(release): bump version to `0.23.1`

- src/raw_client.rs
Previously, we'd already assume `use-rustls` to use the default `aws-lc-rs` provider and `use-rustls-ring` to use the `ring` `CryptoProvider`, e.g., for `NoCertificateVerification`.
However, we **wouldn't** actually install the respective provider based on the features, leading to a **reachable** panic at runtime when user tried to access `ssl://` Electrum servers.
Here, we fix this omission and install the default provider according to the configured features.
(cc @oleonardolima @thunderbiscuit)
> Install `rustls`'s `CryptoProvider` based on features

- src/api.rs
- src/batch.rs
- src/client.rs
- src/raw_client.rs
partially addresses https://github.com/bitcoindevkit/bdk/issues/1987
- adds the new batch method for `blockchain.transaction.get_merkle`.
- adds a new test for `batch_transaction_get_merkle` with 3 different
txids and block_heights.
> feat: add `batch_transaction_get_merkle`

- CHANGELOG.md
- Cargo.toml
fixes #173
- bump the crate version to `0.24.0`.
- updates the `CHANGELOG.md` with relevant changes: https://github.com/bitcoindevkit/rust-electrum-client/compare/0.24.0...HEAD
> chore(release): bump version to `0.24.0` and update `CHANGELOG.md`
